[package]
name = "mesh-portal-api-server"
version = "0.2.0-rc1"
edition = "2021"
license = "MIT"
homepage ="http://starlane.io/"
readme="README.md"
repository = "https://github.com/mechtronium/mesh-portal"
description = "A server library for the Resource Mesh Portal API."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.48"
mesh-portal = { path="../mesh-portal"}
mesh-portal-versions = { path="../mesh-portal-versions"}
tokio = { version = "1.15.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4", "wasm-bindgen"] }
futures = "0.3.13"
anyhow = "1.0.44"
strum_macros = "0.21.1"
dashmap = "4.0.2"
