[package]
name = "mesh-portal-versions"
version = "0.2.0-rc1"
edition = "2021"
license = "MIT"
homepage ="http://starlane.io/"
readme="README.md"
repository = "https://github.com/mechtronium/mesh-portal"
description = "The raw data types for mesh-portal-api serde."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-nom = { path="../cosmic-nom" }
cosmic-macros-primitive = { path="../cosmic-macros-primitive" }
async-trait = "0.1.48"
lazy_static = "1.4.0"
serde = { version="1.0.69", features=['derive','rc'] }
strum = "0.21.0"
strum_macros = "0.21.1"
nom = "7"
nom-supreme = "0.6.0"
nom_locate = "4.0.0"
bincode = "1.3.3"
semver = { version="1.0.10", features=['serde'] }
regex = "1.5.4"
http = "0.2.6"
http-serde = "1.1.0"
serde_json = "1.0.79"
ariadne = "0.1.5"
chrono = { version="0.4.19", features=["serde"] }
tokio = { version = "1.15.0", features = ["full"] }
dashmap = "4.0.2"
serde_urlencoded = "0.7.1"
enum-ordinalize = "3.1.11"

#tailcall = "0.1.6"
