[package]
name = "mesh-portal-tcp-client"
version = "0.2.0-rc1"
edition = "2021"
description = "Client TCP code for mesh-portal"
license = "MIT"
homepage ="http://starlane.io/"
readme="README.md"
repository = "https://github.com/mechtronium/mesh-portal"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesh-portal = { path="../mesh-portal"}
mesh-portal-tcp-common = { path="../mesh-portal-tcp-common"}
mesh-portal-api-client = { path="../mesh-portal-api-client"}
anyhow = "1.0.44"
tokio = { version = "1.15.0", features = ["full"] }
dashmap = "4.0.2"

async-trait = "0.1.48"
