[package]
name = "cosmic-portal-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-macros = { path="../cosmic-macros"}
mesh-portal= { path="../mesh-portal"}
mesh-portal-versions = { path="../mesh-portal-versions"}

serde = { version="1.0.69", features=['derive','rc'] }
async-trait = "0.1.48"
tokio = { version = "1.15.0", features = ["full"] }
