[package]
name = "mesh-portal-tcp-server"
version = "0.2.0-rc1"
edition = "2021"
description = "TCP server for mesh-portal"
license = "MIT"
homepage ="http://starlane.io/"
readme="README.md"
repository = "https://github.com/mechtronium/mesh-portal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesh-portal =  {path="../mesh-portal"}
mesh-portal-api-server = {path="../mesh-portal-api-server"}
mesh-portal-tcp-common = {path="../mesh-portal-tcp-common"}
anyhow = "1.0.44"
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.48"
strum = "0.21.0"
strum_macros = "0.21.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
bincode = "1.3.3"
serde = { version="1.0.69", features=['derive','rc'] }
