[package]
name = "cosmic-hyperlane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesh-portal-versions = { path="../mesh-portal-versions"}
async-trait = "0.1.48"
futures = {version = "0.3.21", default-features = true }
tokio = { version = "1.15.0", features = ["full"] }
dashmap = "5.3.4"
semver = { version="1.0.10", features=['serde'] }

