[package]
name = "starlane-platform-for-postgres-registry"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
description.workspace = true
version.workspace = true

[dependencies]
starlane-macros = { workspace = true }
starlane-space = { workspace = true }
starlane-hyperspace = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
async-trait = { workspace = true }
