[package]
name = "my-app"
version = "0.1.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]

[dependencies]

mechtron= "0.2.0-rc1"
mechtron-common= "0.2.0-rc1"
wasm_membrane_guest = "0.2.0"
mesh-portal= "0.2.0-rc1"

handlebars = "4.2.1"
serde_json = "1.0.79"
lazy_static = "1.4.0"


# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
#wee_alloc = { version = "0.4.5", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
